
version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    container_name: mini_lms_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
